### ISSUE TITLE
Normalization Issue

### ISSUE THREAD

**Issue by kgleach** [ElectroweakGroup/Database_Extraction_Tool#8]
@matmarti There is something wrong with the energies in the ENSDF systematics data (see plot below).  This seems to be true for all cases right now.
![1zn_299zn3-_every_1_fil](https://user-images.githubusercontent.com/29310906/27304583-beca5f42-54fb-11e7-9f5e-e37137a87a19.gif)

**Comment by matmarti** [comment]
![1zn_299zn3-_every_1_fil](https://user-images.githubusercontent.com/25960406/27306153-d0dc0d38-5501-11e7-9613-01d0fe25fd77.png)

No clue how to actually attach pictures here, but I have attached an updated picture using the inputs you did. We now have the code plotting the ground state no matter what spins you input so that the energies match up better. We can talk about this further at the meeting tomorrow, but this is where the program is at. If you download the master again then you should get the same result
